blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/mkosir/react-parallax-tilt/discussions
    about: Ask questions and discuss topics with other community members
